DROP TABLE IF EXISTS USER;
CREATE TABLE USER
{
    userid INT(10) NOT NULL;
    userName VARCHAR(20) NULL DEFAULT NULL;
    firstName VARCHAR(20) NULL DEFAULT NULL;
    lastName VARCHAR(20) NULL DEFAULT NULL;
    password VARCHAR(20) NULL DEFAULT NULL;
    confirmPassword VARCHAR(20) NULL DEFAULT NULL;
    email VARCHAR(20) NULL DEFAULT NULL;
    phNo INT(11);

    PRIMARY KEY('userid')
}